name: Ecs deployment

on:
  workflow_dispatch:
    inputs:
      deployment:
        description: "Type yes to continue"
        required: true
        type: string

  push:
    branches:
      - main
  
  permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: ecsv2repo
  CODEDEPLOY_APP: ecsv2
  CODEDEPLOY_GROUP: deployment_gc
  S3_BUCKET: blue-green-848153448908-codedeploy-revisions
  TASK_FAMILY: memo-task
  CONTAINER_NAME: memos

jobs:
  apply:
    runs-on: ubuntu-24.04
    if: github.event_name == 'push' || github.event.inputs.deployment == 'yes'

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition $TASK_FAMILY \
            --query taskDefinition > task-definition.json

      - name: Register new task definition
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          IMAGE_URI=$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

          jq --arg IMAGE "$IMAGE_URI" --arg NAME "$CONTAINER_NAME" '
            .containerDefinitions |= map(
              if .name == $NAME then .image = $IMAGE else . end
            )
            | del(
              .taskDefinitionArn,
              .revision,
              .status,
              .requiresAttributes,
              .compatibilities,
              .registeredAt,
              .registeredBy
            )
          ' task-definition.json > new-task-definition.json

          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-task-definition.json \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)

          echo "NEW_TASK_DEF_ARN=$NEW_TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Update AppSpec with new task definition
        run: |
          sed -i "s|<TASK_DEFINITION>|$NEW_TASK_DEF_ARN|g" appspec.yml
          cat appspec.yml

      - name: Upload AppSpec to S3
        run: |
          zip appspec.zip appspec.yml
          aws s3 cp appspec.zip s3://${{ env.S3_BUCKET }}/appspec.zip

      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODEDEPLOY_APP }} \
            --deployment-group-name ${{ env.CODEDEPLOY_GROUP }} \
            --s3-location bucket=${{ env.S3_BUCKET }},key=appspec.zip,bundleType=zip